
import { 
    ElButton, 
    ElSelect, 
    ElInput, 
    ElForm, 
    ElFormItem, 
    ElContainer, 
    ElHeader, 
    ElMain, 
    ElAside, 
    ElFooter, 
    ElSubmenu, 
    ElMenu, 
    ElMenuItemGroup, 
    ElMenuItem, 
    ElIcon,
    ElAvatar,
    ElLink,
    ElCheckbox,
    ElDropdown,
    ElDropdownItem,
    ElDropdownMenu,
    ElTag,
    ElCol,
    ElRow,
    ElDivider,
    ElProgress,
    ElTable,
    ElTableColumn,
    ElTabs,
    ElTabPane,
    ElEmpty
} from 'element-plus';

let components = [
    ElButton, 
    ElSelect, 
    ElInput, 
    ElForm, 
    ElFormItem, 
    ElContainer, 
    ElHeader, 
    ElMain, 
    ElAside, 
    ElFooter, 
    ElSubmenu, 
    ElMenu, 
    ElMenuItemGroup, 
    ElMenuItem, 
    ElIcon,
    ElAvatar,
    ElLink,
    ElCheckbox,
    ElDropdown,
    ElDropdownItem,
    ElDropdownMenu,
    ElTag,
    ElCol,
    ElRow,
    ElDivider,
    ElProgress,
    ElTable,
    ElTableColumn,
    ElTabs,
    ElTabPane,
    ElEmpty
]

export default components